import type { Metadata } from 'next'

// CLERK
import {
  ClerkProvider,
} from '@clerk/nextjs'

import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'LocalHost',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

// Can i use this space to navigate teh user out of the app if no location?  or is middlewear teh right place?


  return (
    <ClerkProvider>
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {children}

      </body>
    </html>
    </ClerkProvider>
  )
}